# -*- coding: utf-8 -*-
"""AttitudeAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GlATSZD-OHmg8dU2tlQERJ5LxeMhzRGi
"""

import jieba
import jieba.posseg as pseg
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# count POS occurances
counts = {}
file = open("/content/atti.txt", "r", encoding='utf-8').read()
words = jieba.lcut(file)
for word in words:
    if len(word) == 1: #exclude single character segmentation result
        continue
    else:
        counts[word] = counts.get(word,0) + 1
items = list(counts.items())
items.sort(key=lambda x:x[1], reverse=True)
# display the top occurances of words 
for i in range(10):
     word, count = items[i]
     print ("{0:<10}{1:>5}".format(word, count))

def create_word_cloud(filename):
    text = open("{}.txt".format(filename)).read()
    wordlist = jieba.cut(text, cut_all=True)
    wl = " ".join(wordlist)
    wordcloud = WordCloud(
        background_color="white",
        font_path = "/content/NotoSansSC-Regular.otf",
        max_words=100,
        height=1200,
        width=1600,
                 # Set the font maximum
        max_font_size=200,
                 # Set how many random generation states, that is, how many color schemes there are
        random_state=100,
       )
    myword = wordcloud.generate(wl) #Generate word cloud
    plt.imshow(myword)
    plt.axis("off")
    plt.show()
    wordcloud.to_file('p.png') # Save the word cloud
if __name__ == '__main__':
  create_word_cloud("/content/atti")



